### ISSUE TITLE
DRDY always needed

### ISSUE THREAD

**Issue by awatterott** [ftruzzi/HDC1000-Arduino#1]
Hi,
the variable __drdyn_pin_ is not set with HDC1000(0x40, -1). Therefore DRDY is always needed.

Patch for HDC1000.cpp:

```
HDC1000::HDC1000(uint8_t address, int drdyn_pin){
  _addr = address;

  if(drdyn_pin != -1){
    _drdyn_pin = drdyn_pin;
    pinMode(_drdyn_pin, INPUT);
  }
  els
  {
    _drdyn_pin = -1;
  }
}
```

**Comment by ftruzzi** [comment]
Whoops, I didn't notice that. Thanks for the heads-up!

I also found out that I had declared the _drdyn_pin variable as unsigned, so it couldn't take negative values (it became 255 if I'm not mistaken).

I'm fixing this in a slightly different way:

```
HDC1000::HDC1000(uint8_t address, int drdyn_pin){
    _addr = address;
    _drdyn_pin = drdyn_pin;

    if(_drdyn_pin > -1) pinMode(_drdyn_pin, INPUT);
}
```

The drdyn_pin variable is set to -1 by default in the HDC1000.h file, so you can declare your sensor like this:

```
HDC1000 mySensor(address);
```

and the DRDY function will be off by default.

**Comment by awatterott** [comment]
Thanks. Yes, your solution is smarter :-)
